name: PR Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download cpak binary
        run: |
          curl -sSL \
            -o cpak \
            https://github.com/Containerpak/cpak/releases/download/continuous/cpak
          chmod +x cpak

      - name: Find changed manifests
        id: changes
        run: |
          git fetch origin main
          files=$(git diff --name-only origin/main HEAD \
            | grep '^categories/.*/cpak.json$' || true)
          echo "::set-output name=files::$files"

      - name: Validate local manifest schema
        if: steps.changes.outputs.files != ''
        run: |
          for f in ${{ steps.changes.outputs.files }}; do
            echo "Validating schema of $f"
            ./scripts/validate-manifest-schema.sh "$f"
          done

      - name: Validate remote manifest schema
        if: steps.changes.outputs.files != ''
        run: |
          for f in ${{ steps.changes.outputs.files }}; do
            origin=$(echo "$f" \
              | sed -E 's|categories/[^/]*/||; s|/cpak.json$||; s|github/com|github.com|')
            url="https://raw.githubusercontent.com/${origin}/main/cpak.json"
            echo "Fetching remote manifest: $url"
            curl -sSL "$url" -o remote.json
            echo "Validating schema of remote manifest"
            ./scripts/validate-manifest-schema.sh remote.json
          done

      - name: Test install of added cpak
        if: steps.changes.outputs.files != ''
        run: |
          for f in ${{ steps.changes.outputs.files }}; do
            origin=$(echo "$f" \
              | sed -E 's|categories/[^/]*/||; s|/cpak.json$||; s|github/com|github.com|')

            # extract exactly one of branch|commit|release
            BRANCH=$(jq -r '.branch // ""' "$f")
            COMMIT=$(jq -r '.commit // ""' "$f")
            RELEASE=$(jq -r '.release // ""' "$f")
            count=$(printf "%s\n%s\n%s\n" "$BRANCH" "$COMMIT" "$RELEASE" \
              | grep -cve '^$')
            if [ "$count" -ne 1 ]; then
              echo "ERROR: manifest for $origin must set exactly one of"
              echo "       branch, commit or release"
              exit 1
            fi

            # build install flags
            args=()
            [ -n "$BRANCH" ]  && args+=(--branch "$BRANCH")
            [ -n "$COMMIT" ]  && args+=(--commit "$COMMIT")
            [ -n "$RELEASE" ] && args+=(--release "$RELEASE")

            echo "→ Installing $origin ${args[*]}"
            ./cpak install "$origin" "${args[@]}"
          done
